### ISSUE TITLE
Обновление `grpc-identity`

### ISSUE THREAD

**Issue by sollidy** [atls/nestjs#240]
### С чем связан запрос на фичу?

 Обновление зависимостей в репозитории `grpc-identity`

### Расскажите как вы это себе видите

Необходимо обновить все зависимости пакета. `@nestjs/...` выше мажорной 8 версии не ставить.

### Критерий успеха

- `yarn check` без ошибок
- `yarn test unit` без ошибок
- `build` или `prepack`: опционально по наличию команды
- `yarn` логи пофикшены предупреждения зависимостей

### Материалы

Интерактивный апгрейд через `yarn`:
- [`yarn upgrade-interactive`](https://yarnpkg.com/cli/upgrade-interactive/)

**Comment by zigfrei** [comment]
Все зависимости кроме `jwks-rsa` и `get-port` обновились до последних. 

При обновлении `jwks-rsa` выше версии 2.1.4 `yarn check`выдает ошибку :

`Erro: Conflicting definitions for 'express-serve-static-core' found at '/home/zigfrei/.yarn/berry/cache/@types-express-serve-static-core-npm-4.17.36-87a82f5a6b-9.zip/node_modules/@types/express-serve-static-core/index.d.ts' and '/home/zigfrei/.yarn/berry/cache/@types-express-serve-static-core-npm-4.17.24-cd6b9fd3ba-9.zip/node_modules/@types/express-serve-static-core/index.d.ts'.`

 `Consider installing a specific version of this library to resolve the conflict.
 The file is in the program because:  
Type library referenced via 'express-serve-static-core' from file '/home/zigfrei/.yarn/berry/cache/@types-express-npm-4.17.13-0e12fe9c24-9.zip/node_modules/@types/express/index.d.ts' with packageId '@types/express-serve-static-core/index.[d.ts@4.17.24](mailto:d.ts@4.17.24)'
 Imported via 'express-serve-static-core' from file '/home/zigfrei/.yarn/berry/cache/@types-express-npm-4.17.13-0e12fe9c24-9.zip/node_modules/@types/express/index.d.ts' with packageId '@types/express-serve-static-core/index.[d.ts@4.17.24](mailto:d.ts@4.17.24)'
Type library referenced via 'express-serve-static-core' from file '/home/zigfrei/.yarn/berry/cache/@types-express-npm-4.17.17-46fe8173db-9.zip/node_modules/@types/express/index.d.ts' with packageId '@types/express-serve-static-core/index.d.ts@4.17.36'`
@SlumberyDude предлагаю поднять `jwks-rsa` на версию 2.1.4 и делать ПР

**Comment by SlumberyDude** [comment]
@zigfrei 
Ошибка связана с экспрессом и его типами. У меня была такая в `http-proxy` модуле, поправил снижением версий, можешь попробовать.

Еще длинные логи заворачивай в тег `<details> </deatils>`
<details> Вот такой </deatils>

**Comment by zigfrei** [comment]
@SlumberyDude изначально `"jwks-rsa": "^2.0.5"` максимальная версия до ошибки экспресса и его типов `"jwks-rsa": "2.1.4"`
> поправил снижением версий, можешь попробовать.

Снижением версии `jwks-rsa`?

**Comment by SlumberyDude** [comment]
@zigfrei 
> Снижением версии jwks-rsa?

Не, я снижал экспресс вроде, там не было `jwks-rsa`. Еще странно что обновление jwks-rsa дает ошибку по типам в экспрессе. Еще нигде пути не фигурируют в логах. Попробуй разобраться в чем тут дело.

У тебя конфликтуют 2 модуля `@types-express-serve-static-core` в дереве зависимостей потому что один из них `4.17.36` а другой `4.17.24`. Первый является зависимостью `@types-express-npm-4.17.17` а другой `@types-express-npm-4.17.13`. Если привести их к одному патчу, то может удастся пофиксить.

**Comment by zigfrei** [comment]
В модуле `@types/express@npm:4.17.13` пропатчил `"@types/express-serve-static-core": "^4.17.18"` до версии `"@types/express-serve-static-core": "^4.17.33"` после чего `yarn check` прошел без ошибок
